#!/bin/bash

# 실행 권한 부여
chmod +x "$0"

echo "========================================================"
echo "🤖 트레이딩 봇 통합 설치 및 설정 마법사 (Multi-Account Edition)"
echo "   각 봇마다 서로 다른 계정의 API Key를 설정할 수 있습니다."
echo "========================================================"

# 함수: .env 파일 생성 및 업데이트
setup_env() {
    local dir=$1
    local name=$2
    local exchange=$3
    
    echo ""
    echo "--------------------------------------------------------"
    echo "🔑 [$name] 설정 ($exchange)"
    echo "--------------------------------------------------------"
    
    if [ ! -d "$dir" ]; then
        echo "❌ 폴더를 찾을 수 없음: $dir"
        return
    fi
    
    # .env 파일 준비
    ENV_FILE="$dir/.env"
    if [ ! -f "$ENV_FILE" ]; then
        if [ -f "$dir/.env.example" ]; then
            cp "$dir/.env.example" "$ENV_FILE"
        else
            touch "$ENV_FILE"
        fi
    fi
    
    # API 키 입력 여부 확인
    read -p "👉 이 봇의 API Key를 설정하시겠습니까? (y/n) [Enter=Skip]: " setup_choice
    if [[ "$setup_choice" == "y" || "$setup_choice" == "Y" ]]; then
        read -p "   API Key 입력: " api_key
        read -p "   Secret Key 입력: " secret_key
        
        # 기존 내용 비우고 새로 쓰거나, sed로 교체하는 방식보다 
        # 깔끔하게 새로 작성하는 것이 안전함 (변수명이 고정되어 있으므로)
        
        echo "# Auto-generated by install.sh" > "$ENV_FILE"
        
        if [[ "$exchange" == "Binance" ]]; then
            echo "BINANCE_API_KEY=$api_key" >> "$ENV_FILE"
            echo "BINANCE_SECRET=$secret_key" >> "$ENV_FILE"
            echo "TRADING_MODE=live" >> "$ENV_FILE" # 실전 모드 기본값
            echo "SYMBOL=BTC/USDT" >> "$ENV_FILE"
        elif [[ "$exchange" == "Bybit" ]]; then
            echo "BYBIT_API_KEY=$api_key" >> "$ENV_FILE"
            echo "BYBIT_API_SECRET=$secret_key" >> "$ENV_FILE"
            echo "TRADING_MODE=live" >> "$ENV_FILE"
            echo "SYMBOL=BTC/USDT" >> "$ENV_FILE"
        fi
        
        echo "✅ $dir/.env 설정 완료!"
    else
        echo "   ➜ 건너뜀 (기존 설정 유지)"
    fi
}

# 1. 봇별 설정 진행
setup_env "Deploy_15m" "1. 15분봉 봇 (1.1억 전략)" "Binance"
setup_env "Bybit_1h"   "2. 1시간봉 봇 (4.1억 전략)" "Bybit"
setup_env "Real_5m"    "3. 5분봉 봇 (Crazy Bull)" "Binance"
setup_env "BTC_30m"    "4. 30분봉 봇 (안정형)" "Binance"
setup_env "Ultimate_100m" "5. 👑 1억 목표 최종 봇 (7618배)" "Binance"

echo ""
echo "========================================================"
echo "🐳 Docker 환경 구성 및 실행"
echo "========================================================"

# 2. Docker 설치 확인
if ! command -v docker &> /dev/null; then
    echo "📦 Docker를 설치합니다... (관리자 권한 필요)"
    
    sudo apt-get update
    sudo apt-get install -y ca-certificates curl gnupg lsb-release
    
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      
    sudo apt-get update
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-compose
    sudo usermod -aG docker $USER
    echo "✅ Docker 설치 완료."
else
    echo "✅ Docker가 이미 설치되어 있습니다."
fi

# 3. Docker Compose 실행
echo "🚀 봇 컨테이너 실행 중..."

if docker compose version &> /dev/null; then
    DOCKER_COMPOSE_CMD="docker compose"
elif command -v docker-compose &> /dev/null; then
    DOCKER_COMPOSE_CMD="docker-compose"
else
    echo "❌ Docker Compose를 찾을 수 없습니다."
    exit 1
fi

sudo $DOCKER_COMPOSE_CMD up -d --build

# 4. 자동 실행 설정
echo "🔄 부팅 시 자동 실행 설정..."
sudo systemctl enable docker.service > /dev/null 2>&1
sudo systemctl enable containerd.service > /dev/null 2>&1

echo ""
echo "========================================================"
echo "🎉 모든 설정 및 실행이 완료되었습니다!"
echo ""
echo "각 봇은 설정하신 계정으로 독립적으로 동작합니다."
echo "대박 나세요! �"
echo "========================================================"
