#!/bin/bash

# 실행 권한 부여
chmod +x "$0"
chmod +x start.sh

echo "========================================================"
echo "🛠️  트레이딩 봇 통합 환경 설정 (Setup Wizard)"
echo "    - API Key 설정 및 Docker 환경을 구성합니다."
echo "    - 최초 1회만 실행하시면 됩니다."
echo "========================================================"

# 함수: .env 파일 생성 및 업데이트
setup_env() {
    local dir=$1
    local name=$2
    local exchange=$3
    
    echo ""
    echo "--------------------------------------------------------"
    echo "🔑 [$name] 설정 ($exchange)"
    echo "--------------------------------------------------------"
    
    if [ ! -d "$dir" ]; then
        echo "❌ 폴더를 찾을 수 없음: $dir"
        return
    fi
    
    # .env 파일 준비
    ENV_FILE="$dir/.env"
    if [ ! -f "$ENV_FILE" ]; then
        if [ -f "$dir/.env.example" ]; then
            cp "$dir/.env.example" "$ENV_FILE"
        else
            touch "$ENV_FILE"
        fi
    fi
    
    # API 키 입력 여부 확인
    read -p "👉 이 봇의 API Key를 새로 설정하시겠습니까? (y/n) [Enter=Skip]: " setup_choice
    if [[ "$setup_choice" == "y" || "$setup_choice" == "Y" ]]; then
        read -p "   API Key 입력: " api_key
        read -p "   Secret Key 입력: " secret_key
        
        echo "# Auto-generated by setup.sh" > "$ENV_FILE"
        
        if [[ "$exchange" == "Binance" ]]; then
            echo "BINANCE_API_KEY=$api_key" >> "$ENV_FILE"
            echo "BINANCE_SECRET=$secret_key" >> "$ENV_FILE"
            echo "TRADING_MODE=live" >> "$ENV_FILE"
            echo "SYMBOL=BTC/USDT" >> "$ENV_FILE"
        elif [[ "$exchange" == "Bybit" ]]; then
            echo "BYBIT_API_KEY=$api_key" >> "$ENV_FILE"
            echo "BYBIT_API_SECRET=$secret_key" >> "$ENV_FILE"
            echo "TRADING_MODE=live" >> "$ENV_FILE"
            echo "SYMBOL=BTC/USDT" >> "$ENV_FILE"
        fi
        
        echo "✅ $dir/.env 저장 완료!"
    else
        echo "   ➜ 건너뜀 (기존 설정 유지)"
    fi
}

# 1. 봇별 설정 진행
setup_env "Deploy_15m" "1. 15분봉 봇 (1.1억 전략)" "Binance"
setup_env "Bybit_1h"   "2. 1시간봉 봇 (4.1억 전략)" "Bybit"
setup_env "Real_5m"    "3. 5분봉 봇 (Crazy Bull)" "Binance"
setup_env "BTC_30m"    "4. 30분봉 봇 (안정형)" "Binance"
setup_env "Ultimate_100m" "5. 👑 1억 목표 최종 봇 (7618배)" "Binance"

echo ""
echo "========================================================"
echo "🐳 Docker 환경 확인 및 자동 실행 등록"
echo "========================================================"

# 2. Docker 설치 확인
if ! command -v docker &> /dev/null; then
    echo "📦 Docker를 설치합니다... (관리자 권한 필요)"
    # Docker 설치 스크립트 실행 또는 패키지 설치
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    rm get-docker.sh
    sudo usermod -aG docker $USER
    echo "✅ Docker 설치 완료."
else
    echo "✅ Docker가 이미 설치되어 있습니다."
fi

# 3. 자동 실행 등록 (재부팅 시 Docker 켜짐)
echo "🔄 부팅 시 Docker 자동 실행 설정..."
sudo systemctl enable docker.service > /dev/null 2>&1
sudo systemctl enable containerd.service > /dev/null 2>&1

echo ""
echo "========================================================"
echo "🎉 설정이 모두 완료되었습니다!"
echo "========================================================"
echo ""
echo "아래 명령어로 봇과 대시보드를 시작하세요:"
echo ""
echo "👉 sudo ./start.sh"
echo ""
